/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedSchemesIdRouteImport } from './routes/_authenticated/schemes.$id'
import { Route as AuthenticatedFormsIdRouteImport } from './routes/_authenticated/forms.$id'

const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchemesIdRoute = AuthenticatedSchemesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSchemesRoute,
} as any)
const AuthenticatedFormsIdRoute = AuthenticatedFormsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFormsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forms': typeof AuthenticatedFormsRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/schemes': typeof AuthenticatedSchemesRouteWithChildren
  '/forms/$id': typeof AuthenticatedFormsIdRoute
  '/schemes/$id': typeof AuthenticatedSchemesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forms': typeof AuthenticatedFormsRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/schemes': typeof AuthenticatedSchemesRouteWithChildren
  '/forms/$id': typeof AuthenticatedFormsIdRoute
  '/schemes/$id': typeof AuthenticatedSchemesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRouteWithChildren
  '/_authenticated/forms/$id': typeof AuthenticatedFormsIdRoute
  '/_authenticated/schemes/$id': typeof AuthenticatedSchemesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-callback'
    | '/forms'
    | '/products'
    | '/schemes'
    | '/forms/$id'
    | '/schemes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-callback'
    | '/forms'
    | '/products'
    | '/schemes'
    | '/forms/$id'
    | '/schemes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth-callback'
    | '/_authenticated/forms'
    | '/_authenticated/products'
    | '/_authenticated/schemes'
    | '/_authenticated/forms/$id'
    | '/_authenticated/schemes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schemes/$id': {
      id: '/_authenticated/schemes/$id'
      path: '/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof AuthenticatedSchemesIdRouteImport
      parentRoute: typeof AuthenticatedSchemesRoute
    }
    '/_authenticated/forms/$id': {
      id: '/_authenticated/forms/$id'
      path: '/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AuthenticatedFormsIdRouteImport
      parentRoute: typeof AuthenticatedFormsRoute
    }
  }
}

interface AuthenticatedFormsRouteChildren {
  AuthenticatedFormsIdRoute: typeof AuthenticatedFormsIdRoute
}

const AuthenticatedFormsRouteChildren: AuthenticatedFormsRouteChildren = {
  AuthenticatedFormsIdRoute: AuthenticatedFormsIdRoute,
}

const AuthenticatedFormsRouteWithChildren =
  AuthenticatedFormsRoute._addFileChildren(AuthenticatedFormsRouteChildren)

interface AuthenticatedSchemesRouteChildren {
  AuthenticatedSchemesIdRoute: typeof AuthenticatedSchemesIdRoute
}

const AuthenticatedSchemesRouteChildren: AuthenticatedSchemesRouteChildren = {
  AuthenticatedSchemesIdRoute: AuthenticatedSchemesIdRoute,
}

const AuthenticatedSchemesRouteWithChildren =
  AuthenticatedSchemesRoute._addFileChildren(AuthenticatedSchemesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFormsRoute: AuthenticatedFormsRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
