/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthCallbackImport } from './routes/auth-callback'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedSchemesImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedProductsImport } from './routes/_authenticated/products'
import { Route as AuthenticatedFormsImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedSchemesIdImport } from './routes/_authenticated/schemes.$id'
import { Route as AuthenticatedFormsIdImport } from './routes/_authenticated/forms.$id'

// Create/Update Routes

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSchemesRoute = AuthenticatedSchemesImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProductsRoute = AuthenticatedProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFormsRoute = AuthenticatedFormsImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSchemesIdRoute = AuthenticatedSchemesIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSchemesRoute,
} as any)

const AuthenticatedFormsIdRoute = AuthenticatedFormsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFormsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/forms/$id': {
      id: '/_authenticated/forms/$id'
      path: '/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AuthenticatedFormsIdImport
      parentRoute: typeof AuthenticatedFormsImport
    }
    '/_authenticated/schemes/$id': {
      id: '/_authenticated/schemes/$id'
      path: '/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof AuthenticatedSchemesIdImport
      parentRoute: typeof AuthenticatedSchemesImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedFormsRouteChildren {
  AuthenticatedFormsIdRoute: typeof AuthenticatedFormsIdRoute
}

const AuthenticatedFormsRouteChildren: AuthenticatedFormsRouteChildren = {
  AuthenticatedFormsIdRoute: AuthenticatedFormsIdRoute,
}

const AuthenticatedFormsRouteWithChildren =
  AuthenticatedFormsRoute._addFileChildren(AuthenticatedFormsRouteChildren)

interface AuthenticatedSchemesRouteChildren {
  AuthenticatedSchemesIdRoute: typeof AuthenticatedSchemesIdRoute
}

const AuthenticatedSchemesRouteChildren: AuthenticatedSchemesRouteChildren = {
  AuthenticatedSchemesIdRoute: AuthenticatedSchemesIdRoute,
}

const AuthenticatedSchemesRouteWithChildren =
  AuthenticatedSchemesRoute._addFileChildren(AuthenticatedSchemesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFormsRoute: AuthenticatedFormsRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/forms': typeof AuthenticatedFormsRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/schemes': typeof AuthenticatedSchemesRouteWithChildren
  '/forms/$id': typeof AuthenticatedFormsIdRoute
  '/schemes/$id': typeof AuthenticatedSchemesIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/forms': typeof AuthenticatedFormsRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/schemes': typeof AuthenticatedSchemesRouteWithChildren
  '/forms/$id': typeof AuthenticatedFormsIdRoute
  '/schemes/$id': typeof AuthenticatedSchemesIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRouteWithChildren
  '/_authenticated/forms/$id': typeof AuthenticatedFormsIdRoute
  '/_authenticated/schemes/$id': typeof AuthenticatedSchemesIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth-callback'
    | '/forms'
    | '/products'
    | '/schemes'
    | '/forms/$id'
    | '/schemes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth-callback'
    | '/forms'
    | '/products'
    | '/schemes'
    | '/forms/$id'
    | '/schemes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth-callback'
    | '/_authenticated/forms'
    | '/_authenticated/products'
    | '/_authenticated/schemes'
    | '/_authenticated/forms/$id'
    | '/_authenticated/schemes/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/auth-callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/forms",
        "/_authenticated/products",
        "/_authenticated/schemes"
      ]
    },
    "/auth-callback": {
      "filePath": "auth-callback.tsx"
    },
    "/_authenticated/forms": {
      "filePath": "_authenticated/forms.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/forms/$id"
      ]
    },
    "/_authenticated/products": {
      "filePath": "_authenticated/products.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/schemes": {
      "filePath": "_authenticated/schemes.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/schemes/$id"
      ]
    },
    "/_authenticated/forms/$id": {
      "filePath": "_authenticated/forms.$id.tsx",
      "parent": "/_authenticated/forms"
    },
    "/_authenticated/schemes/$id": {
      "filePath": "_authenticated/schemes.$id.tsx",
      "parent": "/_authenticated/schemes"
    }
  }
}
ROUTE_MANIFEST_END */
